Algoritmo ARREGLOS_MULTIPLOS
	DEFINIR TAMAÑO Como Entero
	Escribir "INGRESE TAMAÑO DEL ARREGLO"
	Leer TAMAÑO
	DIMENSION MULTIPLOS[TAMAÑO]
	Escribir "INGRESE NUMERO"
	LEER NUM
	MULTIPLICACION<-0
	Para A<-0 Hasta TAMAÑO-1 Con Paso 1 Hacer
		MULTIPLICACION<-MULTIPLICACION+1
		MULTIPLOS[A]<-NUM*MULTIPLICACION
		
	Fin Para
	Para A<-0 Hasta TAMAÑO-1 Con Paso 1 Hacer
		Escribir MULTIPLOS[A]
	Fin Para
	
FinAlgoritmo
