Algoritmo EDAD_REGALO
	EDAD <- 12
	REGALO <- 10
	Repetir
		EDAD <- EDAD+1
		REGALO <- REGALO*2
		Escribir 'EDAD DE LA PELADA ',EDAD,' TOTAL REGALADO ',REGALO
	Hasta Que REGALO>1000
	Escribir 'EDAD DE LA PELADA ',EDAD,' TOTAL REGALADO ',REGALO
FinAlgoritmo
