//INCLUIMOS ESTA LIBRERIA QUE NOS PERMITE ESCRIBIR EN LA CONSOLA
#include <iostream>
//INCLUIMOS OTRA LIBRERIA QUE ES PARA QUE NO CIERRE NUESTRO PROGRAMA
#include <stdlib.h>
//DECLARACION DE VARIABLES ENTERAS
char LETRA = 'D';
//SI ESCRIBIMOS UN CADENA DE CARACTERES EN UNA VARIABLE CHAR NOS AGARRA LA ULTIMA LETRA Y NOS DARA ERROR PORQUE CHAR SENCILLO ES SOLO PARA UNA LETRA
//SI QUEREMOS UNA VARIABLE CHAR RECOJA TODAS LAS LETRAS HAREMOS LO SIGUIENTE
char* LETRA1 = "CODIGO";
//LO QUE HICIMO FUE AGREGAR UN ASTERICO AL LADO DEL CHAR Y ESCRIBIR LO DE ADENTRO CON DOBLE COMILLA
//DECLARACION DE VARIABLE BOOL
bool VAR= true;
using namespace std;
int main()
{
    cout<<LETRA<<"\n\n"<<endl;
    cout<<LETRA1<<"\n\n"<<endl;
    cout<<VAR<<"\n\n"<<endl;
                         //endl = HACE QUE TERMINE LA FUNCION COUT
    system("PAUSE");
    //EL SYSTEM SE USA PARA QUE EL PROGRAMA NO SE CIERRE DE LA LIBRERIA QUE LLAMAMOS
    return 0;
}
//CUALQUIER NUMERO DIFERENTE A 0 SERA TOMADO COMO TRUE OSEA 1 AL CONRARIO SERA FALSE