#include <iostream>
// #include se le agrega.h al nombre de la libreria se es de de tipo header
//LA MANERA DE INCLUIR FICHERO
#include "iostream"
/* LA DIFERENCIA ENTRE <> Y "" ES QUE CON <> LO QUE VA A HACER ES BUSCARLO EN LA CARPETA INCLUDE EN LA LIBRERIA
DE INCLUDE DEL MISMO PROGRAMA PORQUE YA VIENEN ESCRITAS
CON "" LOS BUSCA EN NUESTRA CARPETA DONDE ESTA GUARDADO EL ARCHIVO C++ LA BUSCA AHI SI NO ESTA LA BUSCA EN LA 
CARPETA DEL PROGRAMA*/