//INCLUIMOS ESTA LIBRERIA QUE NOS PERMITE ESCRIBIR EN LA CONSOLA
#include <iostream>
//INCLUIMOS OTRA LIBRERIA QUE ES PARA QUE NO CIERRE NUESTRO PROGRAMA
#include <stdlib.h>
//DECLARACION DE VARIABLES ENTERAS
int NUM = 34, NUM2=66,SUMA=NUM+NUM2,MULT=NUM*NUM2,RESTA=NUM-NUM2;
using namespace std;
int main()
{
    cout<<SUMA<<"\n\n"<<MULT<<"\n\n"<<RESTA<<endl;
                         //endl = HACE QUE TERMINE LA FUNCION COUT
    system("PAUSE");
    //EL SYSTEM SE USA PARA QUE EL PROGRAMA NO SE CIERRE DE LA LIBRERIA QUE LLAMAMOS
    return 0;
}
